version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=/run/secrets/db_password
      - POSTGRES_USER=tabungan_user
      - POSTGRES_DB=tabungan_db_test
    secrets:
      - db_password
  cache:
    image: redis:6.2-alpine
    ports:
      - '6378:6379'
    volumes:
      - ~/apps/redis:/var/lib/redis/data

secrets:
  db_password:
    file: db_password.txt